SELECT NOW(), CURDATE(), CURTIME();

SELECT YEAR(NOW()); -- YEAR MONTH, DAY, HOUR, MINUTE, SECOND

SELECT DAYNAME(NOW()); -- MONTHNAME,

-- FORMATING DATES AND TIME
SELECT DATE_FORMAT(NOW(), '%M %d %Y'); -- search mysql date format string
SELECT TIME_FORMAT(NOW(), '%H:%i:%S  %p');